### ISSUE TITLE
run  code have a mistakes on db = DataLoader(mini, args.task_num, shuffle=True, num_workers=1, pin_memory=True)

### ISSUE THREAD

**Issue by hongshengxin** [dragen1860/MAML-Pytorch#33]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2018.2.3\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm 2018.2.3\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2018.2.3\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2018.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/NLP/meta-learning/MAML-Pytorch/miniimagenet_train.py", line 110, in <module>
    main()
  File "F:/NLP/meta-learning/MAML-Pytorch/miniimagenet_train.py", line 68, in main
    for step, item in enumerate(db):
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MiniImagenet.__init__.<locals>.<lambda>'

**Comment by xiaofanque** [comment]
Hi, I have the same mistake, did you solve this?

**Comment by howyoungchen** [comment]
did you run it on windows?

**Comment by xiaofanque** [comment]
Yes

**Comment by asker-github** [comment]
I also have this problem. When num_ workers = 0, the code can run. I don't know if anyone knows a good solution.

**Comment by wangtianlei1998** [comment]
''Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss_forward''
I have this problem,I don't konw how to solve it?
