### ISSUE TITLE
omniglot dataset download error

### ISSUE THREAD

**Issue by vegetarianfish** [dragen1860/MAML-Pytorch#58]
Hi, thank you for your code!
The mini-imagenet example is ok.
However, for the omniglot example, errors occured while the program downloading omniglot dataset automatically.
How can I solve this problem?
Here are the details. Thanks!
```
== Downloading https://github.com/brendenlake/omniglot/raw/master/python/images_background.zip
Traceback (most recent call last):
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\anaconda\envs\python36\lib\http\client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\anaconda\envs\python36\lib\http\client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\python36\lib\http\client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\python36\lib\http\client.py", line 1042, in _send_output
    self.send(msg)
  File "D:\anaconda\envs\python36\lib\http\client.py", line 980, in send
    self.connect()
  File "D:\anaconda\envs\python36\lib\http\client.py", line 1440, in connect
    super().connect()
  File "D:\anaconda\envs\python36\lib\http\client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\anaconda\envs\python36\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "D:\anaconda\envs\python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\_study\Grade4-1\GraduateDesign\MAML\dragen1860-MAML-Pytorch-master\omniglot_train.py", line 95, in <module>
    main(args)
  File "d:\_study\Grade4-1\GraduateDesign\MAML\dragen1860-MAML-Pytorch-master\omniglot_train.py", line 46, in main
    imgsz=args.imgsz)
  File "d:\_study\Grade4-1\GraduateDesign\MAML\dragen1860-MAML-Pytorch-master\omniglotNShot.py", line 29, in __init__
    lambda x: x/255.])
  File "d:\_study\Grade4-1\GraduateDesign\MAML\dragen1860-MAML-Pytorch-master\omniglot.py", line 33, in __init__
    self.download()
  File "d:\_study\Grade4-1\GraduateDesign\MAML\dragen1860-MAML-Pytorch-master\omniglot.py", line 78, in download
    data = urllib.request.urlopen(url)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\anaconda\envs\python36\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

**Comment by leoeooe** [comment]
you need vpn
